export const IMAGES = {
  logo: require('./Images/logo.png'),
  mapImp: require('./Images/MapImg.png'),
  catImg: require('./Images/catImg.png'),
  userImg: require('./Images/userImg.png'),
  Coins: require('./Images/Coins.png'),
  Wallet: require('./Images/Wallet.png'),
  Bell: require('./Images/Bell.png'),
  // BellNotificationBell: require('./Images/NotificationBell.png'),
  BackArrow: require('./Images/BackArrowe.png'),
  Crown: require('./Images/Crown.png'),
  CoinR: require('./Images/CoinR.png'),
  Setting: require('./Images/Setting.png'),
  Event: require('./Images/Event.png'),
  Grid: require('./Images/Grid.png'),
  Add: require('./Images/Add.png'),
  Chart: require('./Images/Chart.png'),
  Card: require('./Images/CardImage.png'),
  userImage: require('./Images/userImage.png'),
  NoImage: require('./Images/NoImage.png'),
};

export const ANIMATION = {
  Splash: require('./animation/Splash.json'),
  Refresh: require('./animation/Refresh.json'),
  FlamaCoin: require('./animation/Coin.json'),
  Shorts: require('./animation/Chat.json'),
  Post: require('./animation/Post.json'),
  Refer: require('./animation/Refer.json'),
  Notification: require('./animation/Notification.json'),
  Coinfalling: require('./animation/Coinfalling.json'),
  Gift: require('./animation/Gift.json'),
  Play: require('./animation/Play.json'),
  Bonus: require('./animation/Bonus.json'),
};
